name: deploy-backend-ec2

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend-ec2.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive backend
        run: |
          cd backend
          tar -czf ../backend.tar.gz .

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend.tar.gz"
          target: "${{ secrets.EC2_PATH }}"

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd "${{ secrets.EC2_PATH }}"
            rm -rf backend_release && mkdir -p backend_release
            tar -xzf backend.tar.gz -C backend_release
            cd backend_release
            npm install --production
            # write .env if you keep env in secrets (optional)
            # cat > .env <<EOF
            # MONGO_URI=${{ secrets.MONGO_URI }}
            # JWT_SECRET=${{ secrets.JWT_SECRET }}
            # PORT=5000
            # EOF
            pm2 delete tvms-api || true
            pm2 start server.js --name tvms-api
            pm2 save
